# Generated by Django 4.1.6 on 2023-03-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.CharField(default='00.00', max_length=15),
        ),
    ]
